// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/v1/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_proto_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_proto_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	IsVerified    bool                   `protobuf:"varint,4,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_proto_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetUserResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *GetUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PatchUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	PasswordHash  *string                `protobuf:"bytes,3,opt,name=passwordHash,proto3,oneof" json:"passwordHash,omitempty"`
	IsVerified    *bool                  `protobuf:"varint,4,opt,name=isVerified,proto3,oneof" json:"isVerified,omitempty"`
	Role          *string                `protobuf:"bytes,5,opt,name=role,proto3,oneof" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3,oneof" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchUserRequest) Reset() {
	*x = PatchUserRequest{}
	mi := &file_api_proto_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserRequest) ProtoMessage() {}

func (x *PatchUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserRequest.ProtoReflect.Descriptor instead.
func (*PatchUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *PatchUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PatchUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *PatchUserRequest) GetPasswordHash() string {
	if x != nil && x.PasswordHash != nil {
		return *x.PasswordHash
	}
	return ""
}

func (x *PatchUserRequest) GetIsVerified() bool {
	if x != nil && x.IsVerified != nil {
		return *x.IsVerified
	}
	return false
}

func (x *PatchUserRequest) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *PatchUserRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PatchUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchUserResponse) Reset() {
	*x = PatchUserResponse{}
	mi := &file_api_proto_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserResponse) ProtoMessage() {}

func (x *PatchUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserResponse.ProtoReflect.Descriptor instead.
func (*PatchUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *PatchUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PutUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	IsVerified    bool                   `protobuf:"varint,4,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutUserRequest) Reset() {
	*x = PutUserRequest{}
	mi := &file_api_proto_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutUserRequest) ProtoMessage() {}

func (x *PutUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutUserRequest.ProtoReflect.Descriptor instead.
func (*PutUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *PutUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PutUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PutUserRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *PutUserRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *PutUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PutUserRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PutUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutUserResponse) Reset() {
	*x = PutUserResponse{}
	mi := &file_api_proto_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutUserResponse) ProtoMessage() {}

func (x *PutUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutUserResponse.ProtoReflect.Descriptor instead.
func (*PutUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *PutUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_proto_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DeleteUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_proto_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_proto_v1_user_proto protoreflect.FileDescriptor

const file_api_proto_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"*\n" +
	"\x12CreateUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"<\n" +
	"\x0eGetUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xcf\x01\n" +
	"\x0fGetUserResponse\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\"\n" +
	"\fpasswordHash\x18\x03 \x01(\tR\fpasswordHash\x12\x1e\n" +
	"\n" +
	"isVerified\x18\x04 \x01(\bR\n" +
	"isVerified\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\"\xaa\x02\n" +
	"\x10PatchUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12'\n" +
	"\fpasswordHash\x18\x03 \x01(\tH\x01R\fpasswordHash\x88\x01\x01\x12#\n" +
	"\n" +
	"isVerified\x18\x04 \x01(\bH\x02R\n" +
	"isVerified\x88\x01\x01\x12\x17\n" +
	"\x04role\x18\x05 \x01(\tH\x03R\x04role\x88\x01\x01\x12=\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\tcreatedAt\x88\x01\x01B\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_passwordHashB\r\n" +
	"\v_isVerifiedB\a\n" +
	"\x05_roleB\f\n" +
	"\n" +
	"_createdAt\"#\n" +
	"\x11PatchUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xce\x01\n" +
	"\x0ePutUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\"\n" +
	"\fpasswordHash\x18\x03 \x01(\tR\fpasswordHash\x12\x1e\n" +
	"\n" +
	"isVerified\x18\x04 \x01(\bR\n" +
	"isVerified\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"!\n" +
	"\x0fPutUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"?\n" +
	"\x11DeleteUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"$\n" +
	"\x12DeleteUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xbd\x02\n" +
	"\vauthService\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12<\n" +
	"\tPatchUser\x12\x16.user.PatchUserRequest\x1a\x17.user.PatchUserResponse\x126\n" +
	"\aPutUser\x12\x14.user.PutUserRequest\x1a\x15.user.PutUserResponse\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponseBCZAhttps://github.com/HackMateGolang/authService/api/proto/v1;userpbb\x06proto3"

var (
	file_api_proto_v1_user_proto_rawDescOnce sync.Once
	file_api_proto_v1_user_proto_rawDescData []byte
)

func file_api_proto_v1_user_proto_rawDescGZIP() []byte {
	file_api_proto_v1_user_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_user_proto_rawDesc), len(file_api_proto_v1_user_proto_rawDesc)))
	})
	return file_api_proto_v1_user_proto_rawDescData
}

var file_api_proto_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_v1_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),     // 0: user.CreateUserRequest
	(*CreateUserResponse)(nil),    // 1: user.CreateUserResponse
	(*GetUserRequest)(nil),        // 2: user.GetUserRequest
	(*GetUserResponse)(nil),       // 3: user.GetUserResponse
	(*PatchUserRequest)(nil),      // 4: user.PatchUserRequest
	(*PatchUserResponse)(nil),     // 5: user.PatchUserResponse
	(*PutUserRequest)(nil),        // 6: user.PutUserRequest
	(*PutUserResponse)(nil),       // 7: user.PutUserResponse
	(*DeleteUserRequest)(nil),     // 8: user.DeleteUserRequest
	(*DeleteUserResponse)(nil),    // 9: user.DeleteUserResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_proto_v1_user_proto_depIdxs = []int32{
	10, // 0: user.GetUserResponse.CreatedAt:type_name -> google.protobuf.Timestamp
	10, // 1: user.PatchUserRequest.createdAt:type_name -> google.protobuf.Timestamp
	10, // 2: user.PutUserRequest.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 3: user.authService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 4: user.authService.GetUser:input_type -> user.GetUserRequest
	4,  // 5: user.authService.PatchUser:input_type -> user.PatchUserRequest
	6,  // 6: user.authService.PutUser:input_type -> user.PutUserRequest
	8,  // 7: user.authService.DeleteUser:input_type -> user.DeleteUserRequest
	1,  // 8: user.authService.CreateUser:output_type -> user.CreateUserResponse
	3,  // 9: user.authService.GetUser:output_type -> user.GetUserResponse
	5,  // 10: user.authService.PatchUser:output_type -> user.PatchUserResponse
	7,  // 11: user.authService.PutUser:output_type -> user.PutUserResponse
	9,  // 12: user.authService.DeleteUser:output_type -> user.DeleteUserResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_user_proto_init() }
func file_api_proto_v1_user_proto_init() {
	if File_api_proto_v1_user_proto != nil {
		return
	}
	file_api_proto_v1_user_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_user_proto_rawDesc), len(file_api_proto_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_user_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_user_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_user_proto_msgTypes,
	}.Build()
	File_api_proto_v1_user_proto = out.File
	file_api_proto_v1_user_proto_goTypes = nil
	file_api_proto_v1_user_proto_depIdxs = nil
}
